version: "3"
services:
    composer_installation:
        container_name: composer_installation
        image: composer
        volumes:
            - ./code:/app
        command: composer install --ignore-platform-reqs
    nginx:
        restart: always
        image: nginx
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./default.conf:/etc/nginx/conf.d/default.conf
    php:
        build: .
        restart: always
        image: php:7.4-fpm
        volumes:
            - ./code:/code
            - ./php.ini:/usr/local/etc/php/php.ini
    mysql:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        restart: always
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: root
        ports:
            - "8081:80"
        restart: always
        volumes:
            - ./php.ini:/usr/local/etc/php/php.ini